name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: anishch16
          
          # Your Work Token from Secrets
          extra_plugin_token: ${{ secrets.ANISH_WORK_TOKEN }}
          
          # This tells the action to fetch data for both
          additional_accounts: anishchaulagain16
          
          # Visual Settings
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # IMPORTANT: This flag forces the calendar to include the extra account commits
          plugin_isocalendar_extracommits: yes
          
          # Required to access private data from both accounts
          config_allow_authenticated_users_only: yes
          config_import_reported: yes
