name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use your personal token to allow the action to save the file
          token: ${{ secrets.GITHUB_TOKEN }}
          
          user: anishch16
          base: header, activity, community, repositories, metadata
          
          # Use the Work Token as the 'Extra' token
          extras_tokens: ${{ secrets.ANISH_WORK_TOKEN }}
          additional_accounts: anishchaulagain16
          
          # CRITICAL: Tell the plugin to look at private repositories
          config_allow_authenticated_users_only: yes
          
          # Visuals
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
